build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "vorbis/1.3.5"
    CONAN_USERNAME: "coding3d"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 2

    matrix:
        - CONAN_CURRENT_PAGE: 1
	- CONAN_CURRENT_PAGE: 2

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools
  - conan user # Creqte conan data directory

test_script:
  - C:\Python27-x64\python build.py